# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('multiplier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.IntegerField(default=501)),
                ('status', models.CharField(choices=[('r', 'running'), ('f', 'finished'), ('c', 'cancelled')], default='r', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('score', models.IntegerField(default=501)),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('p', 'pending'), ('d', 'done'), ('v', 'void')], default='p', max_length=1)),
                ('dart1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn1', to='darting.Dart')),
                ('dart2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn2', to='darting.Dart')),
                ('dart3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn3', to='darting.Dart')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darting.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='darting.Player')),
            ],
        ),
    ]
