# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darting', '0002_auto_20170309_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='target',
            field=models.IntegerField(default=51),
        ),
    ]
