# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darting', '0003_auto_20170310_0523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='target',
        ),
        migrations.AlterField(
            model_name='player',
            name='score',
            field=models.IntegerField(default=51),
        ),
    ]
