# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 05:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('darting', '0004_auto_20170310_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='target',
            field=models.IntegerField(default=51),
        ),
    ]
